.alias areaupdate $8000
.alias clearsparemem $8068
.alias inctitleroutine $806E
.alias initializeafterreset $8071
.alias ramvaluetbl $80C8
.alias drawintrobackground $80D0
.alias fadeindelay $80F9
.alias flasheffect $8109
.alias metroidfadein $812C
.alias loadflashtimer $8142
.alias metroidsparkle $814D
.alias metroidfadeout $8163
.alias crosshairs $8182
.alias morecrosshairs $81D1
.alias unusedintroroutine1 $81EE
.alias unusedintroroutine2 $8206
.alias changeintronametable $822E
.alias messagefadein $8243
.alias messagefadeout $8263
.alias delayintroreplay $8283
.alias unusedintroroutine3 $828A
.alias prepintrorestart $82A3
.alias titlescreenoff $82ED
.alias titleroutinereturn $82F3
.alias loadsparkledata $87AB
.alias initsparkledatatbl $87C4
.alias updatesparklesprites $87CF
.alias doonesparkleupdate $87D6
.alias sparkleupdate $87D9
.alias dosparklespritecoord $881A
.alias nibblesubtract $8871
.alias writeintrosprite $887B
.alias loadinitialspritedata $8897
.alias sprite0and4inittbl $88BE
.alias sprite1and5inittbl $88CE
.alias sprite2and6inittbl $88DE
.alias sprite3and7inittbl $88EE
.alias drawcrosshairssprites $88FE
.alias dospritemovement $8963
.alias drawcrosssprites $8976
.alias crossspriteindextbl $89AA
.alias sparkleaddresstbl $89AF
.alias topsparkledatatbl $89B3
.alias bottomsparkledatatbl $89E9
.alias crossspritedatatbl $8A4B
.alias loadpaldata $8A8C
.alias palselecttbl $8A9A
.alias flashintroscreen $8AA7
.alias screenflashpaltbl $8ABD
.alias starpalswitch $8AC7
.alias introstarpntr $8AFF
.alias introstarpal $8B0F
.alias dofadeout $8B5F
.alias fadeoutpaldata $8B6D
.alias fadeinpaldata $8B73
.alias processuniqueitems $8B79
.alias uniqueitemsearch $8B9C
.alias uniqueitemfound $8BB5
.alias loaduniqueitems $8BD4
.alias processnextitem $8C03
.alias processnewitembyte $8C0A
.alias samushasitem $8C39
.alias checkpassword $8C5E
.alias calculatepassword $8C7A
.alias loadpassworddata $8D12
.alias loadtanksandmissiles $8D3D
.alias incrementtonextitem $8DA9
.alias validatepassword $8DDE
.alias narpasswordtbl $8E07
.alias passwordchecksumandscramble $8E17
.alias passwordchecksum $8E21
.alias passwordscramble $8E2D
.alias unscramblepassword $8E4E
.alias loadpasswordchar $8E6C
.alias sixupperbits $8F2D
.alias twolowerandfourupper $8F33
.alias fourlowerandtwoupper $8F46
.alias sixlowerbits $8F5A
.alias consolidatepassword $8F60
.alias sixlowerandtwoupper $8FF1
.alias fourlowerandfivethrutwo $9001
.alias twolowerandsixlower $9011
.alias passwordbitmasktbl $9021
.alias itemdata $9029
.alias clearall $909F
.alias startcontinuescreen $90BA
.alias turnondisplay $90D1
.alias choosestartcontinue $90D7
.alias startconttbl $9118
.alias loadpasswordscreen $911A
.alias enterpassword $9147
.alias loadrowandcolumn $91BF
.alias checkbackspace $91FB
.alias charselectytbl $92B6
.alias charselectxtbl $92BB
.alias cursorpostbl $92C8
.alias initializegame $92D4
.alias restartypostbl $9325
.alias restartxpostbl $9328
.alias initializestats $932B
.alias displaypassword $9359
.alias waitforstart $9394
.alias gameover $939E
.alias passwordtoscreen $93C6
.alias loadpasswordtiles $93F9
.alias displayinputcharacters $940B
.alias passwordrowstbl $943F
.alias prepareppuprocess $9449
.alias prepareerasetiles $9450
.alias unusedintroroutine4 $945F
.alias unusedintroroutine5 $946C
.alias unusedintroroutine6 $948F
.alias unusedintroroutine7 $94AF
.alias unusedintroroutine8 $94DA
.alias palettecolorspointertable $9560
.alias palette00 $9586
.alias palette01 $95AA
.alias palette02 $95CE
.alias palette03 $95F2
.alias palette04 $9616
.alias palette05 $963A
.alias palette06 $965E
.alias palette07 $9682
.alias palette08 $96A6
.alias palette09 $96CA
.alias palette0a $96EE
.alias palette0b $9712
.alias palette0c $9736
.alias palette0d $975A
.alias palette0e $977E
.alias palette0f $97A2
.alias palette10 $97C6
.alias palette11 $97EA
.alias palette12 $97F2
.alias endgamepal0b $9806
.alias endgamepal0c $9819
.alias updatespritecoords $981E
.alias calcdisplacement $9871
.alias decspriteycoord $988A
.alias loadstarsprites $98AE
.alias introstarsdata $98C0
.alias passwordrowtbl $9998
.alias passwordrow0 $99A2
.alias passwordrow1 $99AF
.alias passwordrow2 $99BC
.alias passwordrow3 $99C9
.alias passwordrow4 $99D6
.alias nmiscreenwrite $9A07
.alias exit100 $9A38
.alias restart $9A39
.alias endgame $9AA7
.alias loadendgfx $9AD5
.alias showendsamus $9B1C
.alias endsamusflash $9B34
.alias palchangetable $9B83
.alias samuswave $9B93
.alias endfadeout $9BCD
.alias rollcredits $9BFC
.alias loadcredits $9C45
.alias loadwavesprites $9C7F
.alias loadendsamussprites $9C9A
.alias samusheadspritetble $9CFA
.alias wavepointertable $9D12
.alias jshanduptable $9D1A
.alias jshanddowntable $9D2A
.alias bkhanduptable $9D3A
.alias bkhanddowntable $9D4A
.alias endsamusaddrtbl $9D5A
.alias normalsamus $9D66
.alias backturnedsamus $9D9C
.alias fistraisedsamus $9DD2
.alias helmetoffsamus $9E08
.alias jumpsuitsamus $9E3E
.alias bikinisamus $9E74
.alias loadendstarsprites $9EAA
.alias endstardatatable $9EB8
.alias endgamepalwrite $9F54
.alias endgamepalpntrtbl $9F81
.alias endgamepal00 $9F9B
.alias endgamepal01 $9FBF
.alias endgamepal02 $9FCB
.alias endgamepal03 $9FD7
.alias endgamepal04 $9FE3
.alias endgamepal05 $9FEF
.alias endgamepal06 $9FFB
.alias endgamepal07 $A007
.alias endgamepal08 $A013
.alias endgamepal09 $A02E
.alias endgamepal0a $A049
.alias endmessagestringtbl0 $A1BA
.alias endmessagestringtbl1 $A265
.alias creditspointertbl $A291
.alias worldmap $A53E
.alias copymap $A93E
.alias endsq1data $AC00
.alias endtriangledata $ACF5
.alias endsq2data $ADC5
.alias endnoisedata $AE8E
.alias introsq2data $B000
.alias introtriangledata $B076
.alias introsq1data $B0B9
.alias intronoiseindexdata $B115
.alias drumbeat00sfxdata $B201
.alias drumbeat01sfxdata $B204
.alias drumbeat02sfxdata $B207
.alias drumbeat03sfxdata $B20A
.alias gamepausedsfxdata $B20D
.alias screwattsfxdata $B211
.alias missilelaunchsfxdata $B215
.alias bombexplodesfxdata $B219
.alias samuswalksfxdata $B21D
.alias spitflamesfxdata $B221
.alias samushitsq1sq2sfxdata $B225
.alias bosshitsq2sfxdata $B229
.alias bosshitsq1sfxdata $B22D
.alias incorrectpasswordsq1sfxdata $B231
.alias incorrectpasswordsq2sfxdata $B235
.alias timebombticksfxdata $B239
.alias energypickupsfxdata $B23D
.alias missilepickupsfxdata $B241
.alias metalsfxdata $B245
.alias longrangeshotsfxdata $B249
.alias shortrangeshotsfxdata $B24D
.alias jumpsfxdata $B251
.alias enemyhitsfxdata $B255
.alias bugoutofholesfxdata $B259
.alias wavebeamsfxdata $B25D
.alias icebeamsfxdata $B261
.alias bomblaunch1sfxdata $B265
.alias bomblaunch2sfxdata $B269
.alias samustoballsfxdata $B26D
.alias metroidhitsfxdata $B271
.alias samusdiesfxdata $B275
.alias samusbeepsfxdata $B279
.alias bigenemyhitsfxdata $B27D
.alias statueraisesfxdata $B281
.alias doorsfxdata $B285
.alias choosenextsfxroutinetbl $B289
.alias loadnoisesfxinitflags $B31B
.alias loadnoisesfxcontflags $B322
.alias loadsq1sfxinitflags $B329
.alias loadsq1sfxcontflags $B330
.alias gotosfxcheckflags $B337
.alias loadstrianglesfxinitflags $B33D
.alias loadtrianglesfxcontflags $B344
.alias loadmultisfxinitflags $B34B
.alias loadmultisfxcontflags $B35C
.alias loadsq1flags $B364
.alias loadsq1channelsfx $B368
.alias loadtrianglechannelsfx $B36C
.alias loadnoisechannelsfx $B370
.alias loadsq2channelsfx $B374
.alias loadsfxdata $B376
.alias loadsfxregisters $B384
.alias pausesfx $B38F
.alias soundengine $B3B4
.alias clearsfxflags $B3D6
.alias checkrepeatmusic $B3F0
.alias checkmusicflags $B3FC
.alias initializesoundaddresses $B404
.alias clearspecialaddresses $B40E
.alias clearmusicandsfxaddresses $B41D
.alias clearsounds $B43E
.alias selectsfxroutine $B452
.alias musicbranch00 $B46D
.alias musicbranch01 $B472
.alias updatecontflags $B493
.alias clearcurrentsfxflags $B4A2
.alias incrementsfxframe $B4A9
.alias checksfxflag $B4BD
.alias restoresfxflags $B4EA
.alias sfxflagfound $B4EF
.alias spitflamestbl $B4FB
.alias spitflamesfxstart $B50F
.alias spitflamesfxcontinue $B516
.alias screwattacksfxstart $B52B
.alias screwattacksfxcontinue $B539
.alias incrementperiodindex $B564
.alias missilelaunchsfxstart $B56E
.alias missilelaunchsfxcontine $B57B
.alias bombexplodesfxstart $B583
.alias gotoselectsfxroutine $B587
.alias noisesfxcontinue $B58A
.alias endnoisesfx $B58F
.alias musicbranch02 $B597
.alias samuswalksfxstart $B598
.alias multisfxinit $B5A5
.alias endmultisfx $B5CD
.alias bosshitsfxstart $B5EC
.alias bosshitsfxcontinue $B5F6
.alias writesq1sq2periodlow $B62C
.alias bosshitsfxdatatbl $B63C
.alias samushitsfxcontinue $B650
.alias samushitsfxstart $B673
.alias incorrectpasswordsfxstart $B695
.alias incorrectpasswordsfxcontinue $B6A1
.alias missilepickupsfxtbl $B6A9
.alias missilepickupsfxcontinue $B6B0
.alias musicbranch03 $B6CC
.alias missilepickupsfxstart $B6CD
.alias energypickupsfxcontinue $B6D3
.alias energypickupsfxstart $B6E7
.alias sq1sfxcontinue $B6ED
.alias endsq1sfx $B6F2
.alias samusjumpsfxstart $B703
.alias enemyhitsfxstart $B710
.alias bulletfiresfxstart $B716
.alias haslongbeamsfxstart $B72F
.alias metalsfxstart $B735
.alias selectsfx1 $B739
.alias birdoutofholesfxstart $B73C
.alias bulletfiresfxcontinue $B74F
.alias hasicebeamsfxstart $B75E
.alias hasicebeamsfxcontinue $B765
.alias icebeamsfxdatatbl $B778
.alias wavebeamsfxstart $B77A
.alias wavebeamsfxcontinue $B781
.alias loadsq1periodlow $B7A0
.alias musicbranch10 $B7A6
.alias wavebeamsfxperiodlowtbl $B7A7
.alias wavebeamsfxdislngthtbl $B7A9
.alias dooropenclosesfxstart $B7AC
.alias dooropenclosesfxcontinue $B7CB
.alias beepsfxstart $B7D9
.alias beepsfxcontinue $B7E7
.alias bigenemyhitsfxstart $B7EF
.alias bigenemyhitsfxcontinue $B80E
.alias samustoballsfxstart $B834
.alias samustoballsfxcontinue $B84F
.alias writetriangleperiods $B869
.alias bomblaunchsfxstart $B878
.alias bomblaunchsfxcontinue $B87F
.alias endtrianglesfx $B896
.alias musicbranch04 $B8A6
.alias metroidhitsfxstart $B8A7
.alias metroihitsfxcontinue $B8B1
.alias rndtriangleperiods $B8C3
.alias samusdiesfxstart $B8D2
.alias samusdiesfxcontinue $B8ED
.alias statueraisesfxstart $B921
.alias statueraisesfxcontinue $B940
.alias increasetriangleperiods $B978
.alias decreasetriangleperiods $B98C
.alias dividetriangleperiods $B9A0
.alias setvolumeanddisablesweep $B9E4
.alias resetvolumeindex $B9F3
.alias loadsq1sq2periods $BA08
.alias loadsq1sq2channels $BA37
.alias writesqcntrl0 $BA41
.alias writesq2cntrl0 $BA88
.alias writesq1cntrl0 $BA8C
.alias musicbranch05 $BA90
.alias musicbranch06 $BA95
.alias gotocheckrepeatmusic $BA9D
.alias gotoloadsq1sq2channels $BAA1
.alias loadcurrentmusicframedata $BAA5
.alias incrementtonextchannel $BAB3
.alias loadnextchannelindexdata $BADC
.alias repeatmusicloop $BAF4
.alias startnewmusicloop $BB04
.alias loadmusicchannel $BB1C
.alias loadsounddataindexindex $BB37
.alias noperiodinformation $BB5F
.alias periodinformationfound $BB6E
.alias loadnewmusicframecount $BBA8
.alias sq1sq2inuse $BBB1
.alias loadtrianglecntrl0 $BBB7
.alias addtrianglelength $BBCD
.alias loadnoisechannelmusic $BBDE
.alias initmusicindextbl $BBFA
.alias loadmusictempflags $BC36
.alias loadmusicinitflags $BC3D
.alias continuemusic $BC4B
.alias findmusicinitindex $BC53
.alias add8 $BC64
.alias music00start $BC77
.alias music01start $BC7A
.alias music02start $BC7D
.alias msic03start $BC80
.alias music04start $BC83
.alias music05start $BC86
.alias music04init $BC89
.alias xymusicinit $BC8B
.alias music03init $BC96
.alias music02init $BC9A
.alias music05init $BC9E
.alias music01init $BCA4
.alias music00init $BCAA
.alias volumecntrladdresstbl $BCB0
.alias volumedatatbl1 $BCBA
.alias volumedatatbl2 $BCC5
.alias volumedatatbl3 $BCCF
.alias volumedatatbl4 $BCDA
.alias volumedatatbl5 $BD03
.alias initmusictbl $BD31
.alias itemroomtriangleindexdata $BDCD
.alias itemroomsq1indexdata $BDDA
.alias itemroomsq2indexdata $BDDC
.alias powerupsq1indexdata $BDF7
.alias poweruptriangleindexdata $BE08
.alias powerupsq2indexdata $BE0D
.alias fadeinsq2indexdata $BE1D
.alias fadeintriangleindexdata $BE36
.alias fadeinsq1indexdata $BE3E
.alias touriansq2indexdata $BE47
.alias touriansq1indexdata $BE59
.alias touriantriangleindexdata $BE62
.alias musicnotestbl $BE77
.alias notelengths0tbl $BEF7
.alias notelengths1tbl $BF02
.alias notelengths2tbl $BF0D
.alias initializemusic $BF19
.alias areareset $BFB0
